spring:
  application:
    name: process-file-api

  datasource:
    url: jdbc:postgresql://localhost:5433/boltenergy?characterEncoding=UTF-8&useUnicode=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: "SET NAMES 'UTF8'"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 5000
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

file:
  download:
    url: https://dadosabertos.aneel.gov.br/dataset/57e4b8b5-a5db-40e6-9901-27ca629d0477/resource/4a615df8-4c25-48fa-bbea-873a36a79518/download/ralie-usina.csv
    directory: ./downloads
    cron: "*/30 * * * * *"
